/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.churrasquito;

import java.io.BufferedReader;
import java.io.FileReader;

/**
 *
 * @author usuario
 */
public class nuevo extends javax.swing.JFrame {

    /**
     * Creates new form nuevo
     */
    public nuevo() {
         initComponents();
        lecturadearchivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        partGanadas = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        partPerdidas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hanoi = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        dams = new javax.swing.JButton();
        moves = new javax.swing.JLabel();
        combonames = new javax.swing.JComboBox<>();
        partDejadas = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        masWin = new javax.swing.JLabel();
        masLost = new javax.swing.JLabel();
        masLeaved = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Partidas perdidas:");

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        jLabel5.setText("Partidas ganadas:");

        jLabel1.setText("MENU PRINCIPAL");

        jLabel2.setText("SELECCIONE EL JUEGO QUE DESEA JUGAR");

        jLabel7.setText("Partidas abandonadas:");

        hanoi.setText("TORRE DE HANOI");
        hanoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hanoiActionPerformed(evt);
            }
        });

        jLabel9.setText("Movimientos:");

        dams.setText("DAMAS");
        dams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                damsActionPerformed(evt);
            }
        });

        combonames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combonamesActionPerformed(evt);
            }
        });

        create.setText("Crear");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        jLabel12.setText("Tiempo:");

        Exit.setText("Salir");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        jLabel6.setText("Seleccione su usuario");

        jLabel3.setText("Jugador que mas ha ganado:");

        jLabel8.setText("Jugador que mas ha perdido:");

        jLabel10.setText("Jugador que mas ha abandonado las partidas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(create)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(refresh))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(451, 451, 451)
                        .addComponent(hanoi))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dams)
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Exit)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)))
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(partGanadas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(partPerdidas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(moves, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(partDejadas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(masWin, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(masLeaved, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(masLost, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(combonames, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(605, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dams)
                    .addComponent(hanoi))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create)
                    .addComponent(refresh))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(partGanadas, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel3))
                    .addComponent(masWin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(masLost, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partPerdidas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(masLeaved, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partDejadas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(moves, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Exit)
                .addGap(102, 102, 102))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(combonames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(348, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        try {
            combonames.removeAllItems();
        } catch (Exception e) {

            lecturadearchivo();
        }

    }//GEN-LAST:event_refreshActionPerformed

    private void hanoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hanoiActionPerformed
        torredehanoi torre1 = new torredehanoi(this, false);
        torre1.setnewJ(combonames.getSelectedIndex());
        torre1.setVisible(true);

    }//GEN-LAST:event_hanoiActionPerformed

    private void damsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_damsActionPerformed
        ventanaa damitas =new ventanaa (this, false);
        damitas.setVisible(true);

    }//GEN-LAST:event_damsActionPerformed

    private void combonamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combonamesActionPerformed
 int pos =combonames.getSelectedIndex();
  int mayor=0;
  int mayorp=0;
  int mayoa=0;
  int pg=0;
  int pp=0;
  int pa=0;
        for (int i = 0; i < 5; i++) {
            if(pgT[i]>mayor){
                mayor=pgT[i];
          pg=i;
          
            }
            if(ppT[i]>mayorp){
                mayorp=ppT[i];
            pp=i;
            }
            if(paT[i]>mayoa){
                mayoa=paT[i];
                pa=i;
            }
            
            
            
        }
   masWin.setText(combonames.getItemAt(pg));
   masLost.setText(combonames.getItemAt(pp));
   masLeaved.setText(combonames.getItemAt(pa));
   
   int h=minimohora[pos];
   int m=minimominuto[pos]-10;
   int s=minimosegundo[pos]-10;
   Jugador=pos;
   partGanadas.setText(String.valueOf(pgT[pos]-10));
   partPerdidas.setText(String.valueOf(ppT[pos]-10));
   partDejadas.setText(String.valueOf(paT[pos]-10));
   moves.setText(String.valueOf(mmT[pos]-100));
   time.setText(h+":"+m+":"+s);
    }//GEN-LAST:event_combonamesActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
Renap renap=new Renap(this,false);
renap.setVisible(true);
    

    }//GEN-LAST:event_createActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
  System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed
 int pgT []=new int [5];
    int ppT[]=new int[5];
    int paT[]=new int[5];
    int mmT[]=new int[5];
    String tiempoT[]=new String[5];
    int minimohora[]=new int[5];
    int minimominuto[]= new int[5] ;
    int minimosegundo[]=new int [5];
    int pgD []=new int [5];
    int ppD[]=new int[5];
    int paD[]=new int[5];
    int mmD[]=new int[5];
    String tiempoD[]=new String[5];
    
        public void lecturadearchivo(){
        
    FileReader archivo;
BufferedReader lector;
   



try {
    archivo = new FileReader("/home/usuario/NetBeansProjects/Churrasquito/Usuarios.txt");
    if(archivo.ready()){
        lector =new BufferedReader(archivo);
        String cadena;
        int g=0;
        int p=0;
        int a=0;
        int m=0;
        String time="";
        String nombre;
         int mh=0;
    int mm=0;
    int ms=0;
        
        
        int gD=0;
        int pD=0;
        int aD=0;
        int mD=0;
        String timeD="";
       
        
        int pp=0;
        while ((cadena=lector.readLine())!=null) {
      
            nombre=cadena.substring(2,12);
            g=Integer.parseInt(cadena.substring(13, 15));
            p=Integer.parseInt(cadena.substring(16, 18));
            a=Integer.parseInt(cadena.substring(19, 21));
            m=Integer.parseInt(cadena.substring(22, 25));
         
            mh=Integer.parseInt(cadena.substring(26,27));
            mm=Integer.parseInt(cadena.substring(28,30));
            ms=Integer.parseInt(cadena.substring(31,33));
            
           
            gD=Integer.parseInt(cadena.substring(34, 36));
            pD=Integer.parseInt(cadena.substring(37, 39));
            aD=Integer.parseInt(cadena.substring(40, 42));
            mD=Integer.parseInt(cadena.substring(43, 46));
           timeD=cadena.substring(47,cadena.length());
           
            
            minimohora[pp]=mh;
            minimominuto[pp]=mm;
            minimosegundo[pp]=ms;
           
           pgT[pp]=g;
           ppT[pp]=p;
           paT[pp]=a;
          mmT[pp]=m;
          
            
           pgD[pp]=gD;
           ppD[pp]=pD;
           paD[pp]=aD;
           mmD[pp]=mD;
           tiempoD[pp]=timeD;
            
            
           combonames.insertItemAt(nombre, pp);
            pp=pp+1;
        }

    }else{
        System.out.println("El archivo no esta listo para ser leido");

    }
} catch (Exception e) {
    System.out.println("Error: "+e.getMessage());
}
    
    
    }    int Jugador=0;

    public int getJugador() {
        return Jugador;
    }

    public void setJugador(int nJugador) {
        this.Jugador = nJugador;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JComboBox<String> combonames;
    private javax.swing.JButton create;
    private javax.swing.JButton dams;
    private javax.swing.JButton hanoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel masLeaved;
    private javax.swing.JLabel masLost;
    private javax.swing.JLabel masWin;
    private javax.swing.JLabel moves;
    private javax.swing.JLabel partDejadas;
    private javax.swing.JLabel partGanadas;
    private javax.swing.JLabel partPerdidas;
    private javax.swing.JButton refresh;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
