/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.churrasquito;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author usuario
 */
public class Renap extends javax.swing.JDialog {

    /**
     * Creates new form Renap
     */
    public Renap(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lecturadearchivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newname = new javax.swing.JTextField();
        rename = new javax.swing.JButton();
        combouser = new javax.swing.JComboBox<>();
        endprocess = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        newname.setText(" ");
        newname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newnameActionPerformed(evt);
            }
        });
        newname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newnameKeyTyped(evt);
            }
        });

        rename.setText("Renombrar");
        rename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameActionPerformed(evt);
            }
        });

        combouser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        combouser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combouserActionPerformed(evt);
            }
        });

        endprocess.setText("Finalizar");
        endprocess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endprocessActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Ingrese el nombre a registrar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(endprocess)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rename)
                        .addGap(61, 61, 61))
                    .addComponent(newname, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combouser, javax.swing.GroupLayout.Alignment.LEADING, 0, 201, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(combouser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(newname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rename)
                .addGap(17, 17, 17)
                .addComponent(endprocess)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newnameActionPerformed

    private void newnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newnameKeyTyped
        if(newname.getText().length()>10){
            evt.consume();
        }
    }//GEN-LAST:event_newnameKeyTyped

    private void renameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameActionPerformed
        position =combouser.getSelectedIndex();
        names =newname.getText();
        combouser.removeItemAt(position);
        combouser.insertItemAt(names, position);
        int tn=10-names.length();
        if(names.length()<10){
            for (int i = 0; i <=tn; i++) {
                names+=" ";

            }
        }

        try {
            escribir();
        } catch (IOException ex) {
            Logger.getLogger(Renap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_renameActionPerformed

    private void combouserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combouserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combouserActionPerformed
String nombres[]=new String[5];
        int partidasGanadas []=new int [5];
    int partidasPerdidas[]=new int[5];
    int partidasAbandonadas[]=new int[5];
    int moves[]=new int[5];
    String tiempoT[]=new String[5];
   

   
    public void lecturadearchivo(){
        
    FileReader archivo;
BufferedReader lector;
   



try {
    archivo = new FileReader("/home/usuario/NetBeansProjects/Churrasquito/Usuarios.txt");
    if(archivo.ready()){
        lector =new BufferedReader(archivo);
        String cadena;
        int g=0;
        int p=0;
        int a=0;
        int m=0;
        String time="";
        String nombre;
        
        int gD=0;
        int pD=0;
        int aD=0;
        int mD=0;
        String timeD="";
       
        
        int pp=0;
        while ((cadena=lector.readLine())!=null) {
      
            nombre=cadena.substring(2,12);
            g=Integer.parseInt(cadena.substring(13, 15));
            p=Integer.parseInt(cadena.substring(16, 18));
            a=Integer.parseInt(cadena.substring(19, 21));
            m=Integer.parseInt(cadena.substring(22, 25));
           time=cadena.substring(26,33);
           
            gD=Integer.parseInt(cadena.substring(34, 36));
            pD=Integer.parseInt(cadena.substring(37, 39));
            aD=Integer.parseInt(cadena.substring(40, 42));
            mD=Integer.parseInt(cadena.substring(43, 46));
           timeD=cadena.substring(47,cadena.length());
           
           
           nombres[pp]=nombre;
           partidasGanadas[pp]=g;
           partidasPerdidas[pp]=p;
           partidasAbandonadas[pp]=a;
           moves[pp]=m;
           tiempoT[pp]=time;
       
           combouser.insertItemAt(nombre, pp);
            pp=pp+1;
        }

    }else{
        System.out.println("El archivo no esta listo para ser leido");

    }
} catch (Exception e) {
    System.out.println("Error: "+e.getMessage());
}
    
    
    }
 
    public void escribir () throws IOException{
            
        FileWriter archivo =null;
PrintWriter  escritor =null;
try {
    archivo =new  FileWriter("/home/usuario/NetBeansProjects/Churrasquito/Usuarios.txt");
    escritor =new PrintWriter(archivo);

for (int i = 0; i < 5; i++) {
   
    
    if(i==position){
        escritor.println(position+names+","+"10,10,10,100,0:10:10,10,10,10,100,0:10:10");
    }else{
        escritor.println(i+","+nombres[i]+","+partidasGanadas[i]+","+partidasPerdidas[i]+","+partidasAbandonadas[i]+","+moves[i]+","+tiempoT[i]);
    
    }
    
    
}


} catch (Exception e) {
    System.out.println("Error: " +e.getMessage());
 
}finally{
    archivo.close();
}
    }
    
    
    int position=0;
String names;
    private void endprocessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endprocessActionPerformed

        dispose();
    }//GEN-LAST:event_endprocessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Renap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Renap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Renap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Renap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Renap dialog = new Renap(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combouser;
    private javax.swing.JButton endprocess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField newname;
    private javax.swing.JButton rename;
    // End of variables declaration//GEN-END:variables
}
